### ISSUE TITLE
对窗口大小的检测方法会误伤侧边栏

### ISSUE THREAD

**Issue by daidr** [theajack/disable-devtool#23]
会误伤下面这些情况：
1.Edge的垂直标签页功能开启时
2.任一侧边栏打开时（比如将下载浮窗固定到侧边栏）

**Comment by theajack** [comment]
感谢您的反馈 会在后续版本中修复
@daidr

**Comment by JorgeGNL** [comment]
Hi,

Is there any fix for this issue, some users using Edge are having problems when having the vertical tab enabled?

Please share an update with the fix.

Thanks.

**Comment by theajack** [comment]
@daidr @JorgeGNL 
已修复，请升级到到0.2.3使用
Fixed，Please update to v0.2.3

**Comment by JorgeGNL** [comment]
The issue is still not resolved on v0.2.3.

Let's wait, if others also have the same issue as me.
